"""Pose-based memory retrieval.

A past frame is scored for the chunk being generated by how much of the chunk's
view frustum it already saw, minus a small penalty on camera distance::

    score = fov_overlap(query, candidate) - 0.2 * (||dt|| + 4 * angle)

Everything here is computed from camera poses alone, before any frame is
generated, so retrieval costs nothing on the GPU.
"""

from __future__ import annotations

import collections
import dataclasses

import numpy as np

NEAR, FAR = 2.0, 60.0          # assumed scene depth band, metres
SELECT_LAMBDA = 0.2            # weight on camera distance in the retrieval score


def invert_c2w(c2w: np.ndarray) -> np.ndarray:
    c2w = np.asarray(c2w, dtype=np.float64)
    R, t = c2w[..., :3, :3], c2w[..., :3, 3]
    Rt = np.swapaxes(R, -1, -2)
    out = np.zeros_like(c2w)
    out[..., :3, :3] = Rt
    out[..., :3, 3] = -np.einsum("...ij,...j->...i", Rt, t)
    out[..., 3, 3] = 1.0
    return out


@dataclasses.dataclass
class Frustum:
    """Pinhole camera plus the depth band sampled when scoring overlap."""

    fx: float
    fy: float
    cx: float
    cy: float
    width: int
    height: int
    near: float
    far: float
    grid_uv: int = 8
    grid_depth: int = 4

    @classmethod
    def from_intrinsics(cls, intrinsics, traj_scale: float = 4.0) -> "Frustum":
        """``intrinsics`` = (fx, fy, cx, cy); poses are in metres / ``traj_scale``."""
        fx, fy, cx, cy = (float(v) for v in intrinsics)
        return cls(fx=fx, fy=fy, cx=cx, cy=cy, width=int(round(cx * 2)), height=int(round(cy * 2)),
                   near=NEAR / traj_scale, far=FAR / traj_scale)

    def points(self) -> np.ndarray:
        """Sample points inside the frustum, camera coordinates ``[3, P]``."""
        gu = (np.arange(self.grid_uv) + 0.5) / self.grid_uv * self.width
        gv = (np.arange(self.grid_uv) + 0.5) / self.grid_uv * self.height
        uu, vv = np.meshgrid(gu, gv, indexing="ij")
        bx = (uu.reshape(-1) - self.cx) / self.fx
        by = (vv.reshape(-1) - self.cy) / self.fy
        rays = np.stack([bx, by, np.ones_like(bx)], axis=0)
        e = np.linspace(np.log(self.near), np.log(self.far), self.grid_depth + 1)
        depths = np.exp(0.5 * (e[:-1] + e[1:]))                   # log-spaced bin centres
        return (rays[:, :, None] * depths[None, None, :]).reshape(3, -1)


def fov_overlap(query_c2w: np.ndarray, cand_c2w: np.ndarray, frustum: Frustum) -> np.ndarray:
    """Fraction of the query frustum that each candidate camera also sees. ``[M]``."""
    q = np.asarray(query_c2w, dtype=np.float64)
    cand = np.asarray(cand_c2w, dtype=np.float64)
    if cand.ndim == 2:
        cand = cand[None]
    if cand.shape[0] == 0:
        return np.zeros(0)
    pts_w = q[:3, :3] @ frustum.points() + q[:3, 3:4]
    w2c = invert_c2w(cand)
    pc = np.einsum("mij,jp->mip", w2c[:, :3, :3], pts_w) + w2c[:, :3, 3][:, :, None]
    z = pc[:, 2, :]
    zs = np.clip(z, 1e-9, None)
    u = pc[:, 0, :] * frustum.fx / zs + frustum.cx
    v = pc[:, 1, :] * frustum.fy / zs + frustum.cy
    inside = ((z > frustum.near) & (z < frustum.far)
              & (u >= 0.0) & (u <= frustum.width) & (v >= 0.0) & (v <= frustum.height))
    return inside.mean(axis=1)


def pose_distance(query_c2w: np.ndarray, cand_c2w: np.ndarray, rot_weight: float = 4.0) -> np.ndarray:
    """``||dt|| + rot_weight * angle between optical axes`` (radians). ``[M]``."""
    q = np.asarray(query_c2w, dtype=np.float64)
    cand = np.asarray(cand_c2w, dtype=np.float64)
    if cand.ndim == 2:
        cand = cand[None]
    dt = np.linalg.norm(cand[:, :3, 3] - q[:3, 3], axis=1)
    angle = np.arccos(np.clip(cand[:, :3, 2] @ q[:3, 2], -1.0, 1.0))
    return dt + rot_weight * angle


def topk(query_c2w: np.ndarray, cand_c2w: np.ndarray, frustum: Frustum, k: int) -> np.ndarray:
    """Indices of the ``k`` candidates most useful to a chunk ending at ``query_c2w``."""
    score = np.asarray(fov_overlap(query_c2w, cand_c2w, frustum)).ravel()
    score = score - SELECT_LAMBDA * pose_distance(query_c2w, cand_c2w)
    return np.argsort(-score, kind="stable")[:k]


def select_bank(c2w: np.ndarray, cand_idx: np.ndarray, chunk_end_c2w: np.ndarray,
                frustum: Frustum, k: int, q0: int | None = None, chunk: int = 4,
                cap: int = 60) -> np.ndarray:
    """Memory bank for a block of chunks: the union of each chunk's top-``k``.

    ``chunk_end_c2w[j]`` is the last camera of chunk ``j``. With ``q0`` (the index of
    the first chunk's first frame), chunk ``j`` only considers candidates before
    ``q0 + max(j - 1, 0) * chunk``. If the union exceeds ``cap``, frames requested by
    more chunks are kept first, then newer ones. Returns sorted frame indices.
    """
    cand_idx = np.asarray(cand_idx, dtype=int)
    if len(cand_idx) == 0 or k == 0:
        return np.zeros(0, dtype=int)
    want = []
    for j, q in enumerate(chunk_end_c2w):
        cut = q0 + max(j - 1, 0) * chunk if q0 is not None else cand_idx[-1] + 1
        visible = cand_idx[cand_idx < cut]
        if len(visible):
            want.append(visible[topk(q, c2w[visible], frustum, min(k, len(visible)))])
    if not want:
        return np.zeros(0, dtype=int)
    union = np.unique(np.concatenate(want))
    if len(union) > cap:
        votes = collections.Counter(int(i) for w in want for i in w)
        union = np.array(sorted(union, key=lambda i: (-votes[int(i)], -int(i)))[:cap])
    return np.sort(union)
